services:
  api-shop-service:
    container_name: ShopApp
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - shopapp_backend
    depends_on:
      - postgres

  postgres:
    container_name: shop-postgres-db
    image: postgres:13.3
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - shopapp_backend

networks:
  shopapp_backend:
    external: true  # Đảm bảo sử dụng mạng đã tạo sẵn
    driver: bridge

volumes:
  postgres-data: