server:
  port: 8084
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:5432/shopapp}
    username: ${POSTGRES_USER:postgres_user}
    password: ${POSTGRES_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: /api/v1
jwt:
  expiration: 3600000
  secretKey: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=

#logging:
#  level:
#    root: DEBUG

#debug: true