server:
    port: 8081
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/shopapp}
    driver-class-name: com.mysql.cj.jdbc.Driver
#    8080: docker
    username: ${DATABASE_USER:mysql_user}
    password: ${DATABASE_PASSWORD:mysql_password}
#    username: root
#    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: /api/v1

#logging:
#  level:
#    root: DEBUG

#debug: true