server:
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/shopapp}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER:postgres_user}
    password: ${DATABASE_PASSWORD:postgres_password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: /api/v1
jwt:
  expiration: 3600000
  secretKey: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=

#logging:
#  level:
#    root: DEBUG

#debug: true